module.exports = {
  Service: "Services",
  Legal: "Legal",
  AboutRS: "About RS",
  ServicesDisplayLinksCount: 7,
  legalDisplayedLinksCount: 4,
  aboutUSDisplayedLinksCount: 6,
  loginLabel: "Log In",
  registerButtonLabel: "Register",
  ServiceslDisplayLinksName: "Delivery Options,Large Orders,My Account,Product Returns,Quality Assurance – ISO 9001,Quotes Online,Scheduled Orders,",
  LegalLinknames: "Data Protection,Email Security,Privacy Policy,Website Terms,",
  AboutUSDisplayedLinksNames: "About RS,Careers,Corporate Group,Press Centre,RS Conditions of Sale,World Wide,",
  loginUserName: "MobileTest",
  RSOfficeAddress: "© RS Components Pty Ltd ABN 73 009 403 356, 25 Pavesi St, Smithfield. NSW. 2164 (PO Box 6864, Wetherill Park. NSW. 1851)",
  RSContactNumber: "1300 656 636",
  TalkToUsLabel: "Contact us",
  SocialMediaLinks: 5,
  SocialMediaLinksLabel: "https://twitter.com/RSComponents,https://www.linkedin.com/company/7099/,https://www.youtube.com/channel/UCZ6UzLdlJ8cLRcn5ooclCtA,https://www.instagram.com/rs_components/?hl=en,https://www.facebook.com/RSComponents",
  CompliancelinksLabel: "Website Terms,Privacy Policy,Cookie Policy,Email Security",
  loginPassword: "password",
  logOutText: "Log Out ",
  footer1HeaderFirstLinkHref: "/web/generalDisplay.html?id=aboutRS&file=delivery",
  footer1HeaderSecondLinkHref: "/web/generalDisplay.html?id=services/large-orders",
  footer1HeaderLastLinkHref: "/web/generalDisplay.html?id=services/forward-orders",
  footer2HeaderFirstLinkHref: "/web/generalDisplay.html?id=aboutRS&file=datapolicy",
  footer2HeaderSecondLinkHref: "/web/generalDisplay.html?id=aboutRS/email-security",
  footer2HeaderLastLinkHref: "/web/generalDisplay.html?id=aboutRS&file=terms",
  footer3HeaderFirstLinkHref: "/web/generalDisplay.html?id=aboutRS",
  footer3HeaderSecondLinkHref: "/web/generalDisplay.html?id=footer2",
  footer3HeaderLastLinkHref: "http://www.rs-components.com/",
  weAcceptPaymentTypesLabel: "We accept",
  paymentOptionSource: "/au_payment_options.svg",
  ConnectWithUsLable: "Connect with us",




};
