module.exports = {
  Service: "Services",
  Legal: "Legal (Translation needed)",
  AboutRS: "Über RS",
  ServicesDisplayLinksCount: 6,
  legalDisplayedLinksCount: 5,
  aboutUSDisplayedLinksCount: 6,
  loginLabel: "Log In",
  registerButtonLabel: "Register",
  ServiceslDisplayLinksName: "Alle Produkte,Lieferoptionen,Rücksendungen,Sendungsverfolgung,Technische Beratung,Zahlungsbedingungen,",
  LegalLinknames: "Cookie-Richtlinien,Copyright/Impressum,Datenschutz,E-Mail Sicherheit,Qualität/Zertifikate,",
  AboutUSDisplayedLinksNames: "AGB,Karriere bei RS,Presse-Center,RS weltweit,Unternehmen,Unternehmensgruppe,",
  RSOfficeAddress: "© RS Components GmbH, Mörfelden-Walldorf, Zweigniederlassung Wädenswil, Holzmoosrütistrasse 2a, 8820 Wädenswil - Bankverbindung: Commerzbank Zürich, Kontonummer: 313120166401, BLZ: 8836, SWIFT/BIC: COBACHZHXXX, IBAN: CH63 0883 6120 1664 0100 6",
  RSContactNumber: "044 283 61 90",
  TalkToUsLabel: "call us @",
  SocialMediaLinks: 4,
  SocialMediaLinksLabel: "https://twitter.com/RSOnline_DACH,https://www.linkedin.com/company/7099/,https://www.youtube.com/user/rswwwchannel,https://www.facebook.com/RSDACH",
  CompliancelinksLabel: "Website Terms,Privacy Policy,Cookie Policy,Email Security",
  loginPassword: "password",
  logOutText: "Log Out ",
  footer1HeaderFirstLinkHref: "/web/op/allproducts",
  footer1HeaderSecondLinkHref: "/web/generalDisplay.html?id=services/lieferoptionen",
  footer1HeaderLastLinkHref: "/web/generalDisplay.html?id=services/zahlungsbedingungen",
  footer2HeaderFirstLinkHref: "/web/generalDisplay.html?id=aboutRS/cookiepolicy",
  footer2HeaderSecondLinkHref: "/web/generalDisplay.html?id=aboutRS/copyright_impressum",
  footer2HeaderLastLinkHref: "/web/generalDisplay.html?id=aboutRS/qualitat-umwelt-zertifizierungen",
  footer3HeaderFirstLinkHref: "/web/generalDisplay.html?id=aboutRS/conditions",
  footer3HeaderSecondLinkHref: "/web/generalDisplay.html?id=aboutRS/karriere-center",
  footer3HeaderLastLinkHref: "http://www.electrocomponents.com/",
  weAcceptPaymentTypesLabel: "We accept",
  paymentOptionSource: "/dech_payment_options.svg",
  ConnectWithUsLable: "Connect with us",

};
