module.exports = {
  searchInput_DefaultPlaceholderText: "根据关键字或者产品编号来搜索",
  searchInput_MPN_PlaceholderText: "按零件编号搜索",
  currency_Text: "RMB59.99",
  searchToggleText: "制造商编号",
  searchTerm_lessThan_required_character: " ",
  predictiveSearch_lessThan_ThreeCharacter: "电",
  defaultSearchTerm: "led",
  searchByMPN_SearchTerm: "Ras",
  predictiveSearch_categories_titile: "类别",
  predictiveSearch_brands_title: "品牌",
  predictiveSearch_PartNumber_title: "制造商编号",
  predictiveSearch_StockNumbers_title: "RS 库存编号",
  predictiveSearch_required_Numeric_characters_length: "111",
  predictiveSearch_by_brands: "Irwin",
  predictiveSearch_refine_term: "Irw",
  predictiveSearch_refine_AdditonalLetters:"in",
  browseCategoryHamburgerText: "浏览",
  myAccountLabel:"我的帐户",
  bookOneLabel: "电子元件、电源及连接器",
  bookTwoLabel: "电器、自动化及电缆",
  bookThreeLabel: "机械产品及工具",
  bookFourLabel: "信息技术、测试及安全设备",
  Service: "服务",
  Legal: "法律",
  AboutRS: "关于RS",
  ServicesDisplayLinksCount: 7,
  legalDisplayedLinksCount: 5,
  aboutUSDisplayedLinksCount: 6,
  loginLabel: "Log In",
  registerButtonLabel: "Register",
  ServiceslDisplayLinksName: "产品退货,包裹跟踪,在线报价,大宗订单,我的账户,远期订单,送货方式,",
  LegalLinknames: "数据保护,沪ICP备17030544号-2 欧时电子元件（上海）有限公司 版权所有,私隐条例,网站条款,邮件安全,",
  AboutUSDisplayedLinksNames: "RS销售条款,付款信息,企业集团,全球办事处,关于RS,新闻中心,",
  loginUserName: "MobileTest",
  RSOfficeAddress: "© RS Components Ltd 中国上海市浦东新区东育路227弄3号前滩世贸中心二期C栋5层501单元; 邮编：200126",
  RSContactNumber: "4008201186 (询价热线)",
  AlternativeContactNumber: "4008218857 (售后服务)",
  ContactUsEmail: "R.RSCN@rs-components.com",
  TalkToUsLabel: "联系我们",
  SocialMediaLinks: 2,
  SocialMediaLinksLabel: "http://i.youku.com/rscomponentsapac,http://weibo.com/rscomponents",
  CompliancelinksLabel: "Website Terms,Privacy Policy,Cookie Policy,Email Security",
  loginPassword: "password",
  logOutText: "Log Out ",
  footer1HeaderFirstLinkHref: "/web/generalDisplay.html?id=services/product-returns",
  footer1HeaderSecondLinkHref: "/web/generalDisplay.html?id=services/parcel-tracking",
  footer1HeaderLastLinkHref: "/web/generalDisplay.html?id=services/delivery-methods",
  footer2HeaderFirstLinkHref: "/web/generalDisplay.html?id=aboutRS/datapolicy",
  footer2HeaderSecondLinkHref: "http://www.beian.miit.gov.cn",
  footer2HeaderLastLinkHref: "/web/generalDisplay.html?id=aboutRS/email-security",
  footer3HeaderFirstLinkHref: "/web/generalDisplay.html?id=aboutRS/conditions",
  footer3HeaderSecondLinkHref: "/web/generalDisplay.html?id=footer2",
  footer3HeaderLastLinkHref: "/web/generalDisplay.html?id=footer1",
  weAcceptPaymentTypesLabel: "We accept",
  paymentOptionSource: "/cn_payment_options.svg",
  ConnectWithUsLable: "跟着我们",






};
