module.exports = {
  Service: "Services",
  Legal: "Lovlig",
  AboutRS: "Om RS",
  ServicesDisplayLinksCount: 5,
  legalDisplayedLinksCount: 5,
  aboutUSDisplayedLinksCount: 6,
  loginLabel: "Log In",
  registerButtonLabel: "Register",
  ServiceslDisplayLinksName: "Leveringsmuligheder,Online tilbud,Ordrer til senere levering,Pakkesporing,Returnering af varer,",
  LegalLinknames: "Certificering,Cookie Policy,Datasikkerhed,Email-sikkerhed,Webforbehold,",
  AboutUSDisplayedLinksNames: "Electrocomponents PLC,Job hos RS,Om RS,Pressecenter,RS salgsbetingelser,Verden Rundt,",
  loginUserName: "MobileTest",
  RSOfficeAddress: "RS Components A/S Nattergalevej 6 2400 København NV",
  RSContactNumber: "38 16 99 00",
  TalkToUsLabel: "Kontakt os",
  SocialMediaLinks: 3,
  SocialMediaLinksLabel: "https://twitter.com/RSOnline_DK,https://www.linkedin.com/company/7099/,https://www.youtube.com/channel/UCZ6UzLdlJ8cLRcn5ooclCtA",
  CompliancelinksLabel: "Website Terms,Privacy Policy,Cookie Policy,Email Security",
  loginPassword: "password",
  logOutText: "Log Out ",
  footer1HeaderFirstLinkHref: "/web/generalDisplay.html?id=services/levering",
  footer1HeaderSecondLinkHref: "/web/generalDisplay.html?id=services/online-tilbud",
  footer1HeaderLastLinkHref: "/web/generalDisplay.html?id=services/returnering-af-varer",
  footer2HeaderFirstLinkHref: "/web/generalDisplay.html?id=aboutRS&file=datapolicy",
  footer2HeaderSecondLinkHref: "/web/generalDisplay.html?id=aboutRS&file=cookiePolicy",
  footer2HeaderLastLinkHref: "/web/generalDisplay.html?id=aboutRS&file=terms",
  footer3HeaderFirstLinkHref: "http://www.electrocomponents.com/",
  footer3HeaderSecondLinkHref: "/web/generalDisplay.html?id=footer2",
  footer3HeaderLastLinkHref: "http://www.rs-components.com/",
  weAcceptPaymentTypesLabel: "We accept",
  paymentOptionSource: "/dk_payment_options.svg",
  ConnectWithUsLable: "Følg os på",


};
