module.exports = {
  Service: "服務",
  Legal: "法律",
  AboutRS: "關於RS",
  ServicesDisplayLinksCount: 6,
  legalDisplayedLinksCount: 4,
  aboutUSDisplayedLinksCount: 6,
  loginLabel: "Log In",
  registerButtonLabel: "Register",
  ServiceslDisplayLinksName: "大批訂購,我的帳戶,產品退換,網上報價,送貨方法,遠期訂單,",
  LegalLinknames: "數據保護,私隱條例,網站條款,郵件安全,",
  AboutUSDisplayedLinksNames: "RS銷售條款,企業集團,全球辦事處,加入我們,新聞中心,關於RS,",
  loginUserName: "MobileTest",
  RSOfficeAddress: " © RS Components Ltd 香港新界葵涌葵昌路51號九龍貿易中心一座16樓1601室 \"這個網站的所有解釋根據英語版本\"",
  RSContactNumber: "852 2421 9898",
  TalkToUsLabel: "聯繫我們",
  SocialMediaLinks: 2,
  SocialMediaLinksLabel: "https://www.linkedin.com/company/7099/,https://www.youtube.com/watch?v=Smw54uychQ8&list=PLqnIaXrARxXEW0Nv0LWky-wQxzaX73UsT",
  CompliancelinksLabel: "Website Terms,Privacy Policy,Cookie Policy,Email Security",
  loginPassword: "password",
  logOutText: "Log Out ",
  footer1HeaderFirstLinkHref: "/web/generalDisplay.html?id=services/large-orders",
  footer1HeaderSecondLinkHref: "/web/generalDisplay.html?id=services/my-account",
  footer1HeaderLastLinkHref: "/web/generalDisplay.html?id=services/forward-orders",
  footer2HeaderFirstLinkHref: "/web/generalDisplay.html?id=aboutRS&file=datapolicy",
  footer2HeaderSecondLinkHref: "/web/generalDisplay.html?id=aboutRS&file=privacy",
  footer2HeaderLastLinkHref: "/web/generalDisplay.html?id=aboutRS/email-security",
  footer3HeaderFirstLinkHref: "/web/generalDisplay.html?id=aboutRS&file=conditions",
  footer3HeaderSecondLinkHref: "http://www.electrocomponents.com/",
  footer3HeaderLastLinkHref: "/web/generalDisplay.html?id=aboutRS",
  weAcceptPaymentTypesLabel: "我们接受",
  paymentOptionSource: "/hkcn_payment_options.svg",
  ConnectWithUsLable: "跟着我们",



};
