module.exports = {
  searchInput_DefaultPlaceholderText: "キーワード / 型番で検索",
  searchInput_MPN_PlaceholderText: "製造部品番号で検索",
  currency_Text: "￥59",
  searchToggleText: "型番",
  searchTerm_lessThan_required_character: "l",
  predictiveSearch_lessThan_ThreeCharacter: "エ",
  defaultSearchTerm: "led",
  searchByMPN_SearchTerm: "Ras",
  predictiveSearch_categories_titile: "分類",
  predictiveSearch_brands_title: "メーカー",
  predictiveSearch_PartNumber_title: "メーカー型番",
  predictiveSearch_StockNumbers_title: "RS品番",
  predictiveSearch_required_Numeric_characters_length: "111",
  predictiveSearch_by_brands: "Irwin",
  predictiveSearch_refine_term: "Irw",
  predictiveSearch_refine_AdditonalLetters:"in",
  browseCategoryHamburgerText: "参照",
  myAccountLabel:"マイ アカウント",
  bookOneLabel:"電子部品、電源、コネクタ",
  bookTwoLabel:"電気、制御部品、ケーブル",
  bookThreeLabel:"機械製品、工具",
  bookFourLabel: "IT、テスト、安全機器",
  Service: "ヘルプ & サービス",
  Legal: "Legal (Translation needed)",
  AboutRS: "RSについて",
  ServicesDisplayLinksCount: 7,
  aboutUSDisplayedLinksCount: 6,
  loginLabel: "Log In",
  registerButtonLabel: "Register",
  ServiceslDisplayLinksName: "お問合せ,お支払い方法,ご利用規約,マイアカウント（ユーザ登録）,初めてご利用の方へ・よくあるご質問,注文方法,配送・送料",
  AboutUSDisplayedLinksNames: "RSの歴史,Worldwide,プライバシーポリシー,プレスリリース＆お知らせ,会社概要,開発技術者コミュニティ DesignSpark,",
  LegalLinknames: "ご利用規約,プライバシーポリシー,会社概要",
  loginUserName: "MobileTest",
  RSOfficeAddress: "© アールエスコンポーネンツ株式会社 〒240-0005 神奈川県横浜市保土ヶ谷区神戸町134番地 横浜ビジネスパーク ウエストタワー12階",
  RSContactNumber: "カスタマーサービス 045-335-8888",
  TalkToUsLabel: "お問い合わせ",
  SocialMediaLinks: 4,
  SocialMediaLinksLabel: "https://www.facebook.com/RSJapan,https://twitter.com/RSJapanMK/,https://www.youtube.com/watch?v=hzR0uaQsKZE&list=PLqnIaXrARxXHe9iCub2VWxJhbd8eIzW05,https://www.linkedin.com/company/7099/",
  CompliancelinksLabel: "Website Terms,Privacy Policy,Cookie Policy,Email Security",
  loginPassword: "password",
  logOutText: "Log Out ",
  footer1HeaderFirstLinkHref: "/web/generalDisplay.html?id=our-services/contact",
  footer1HeaderSecondLinkHref: "/web/generalDisplay.html?id=our-services/payment",
  footer1HeaderLastLinkHref: "/web/generalDisplay.html?id=our-services/delivery",
  footer3HeaderFirstLinkHref: "/web/generalDisplay.html?id=our-services/history",
  footer3HeaderSecondLinkHref: "http://www.rs-components.com/",
  footer3HeaderLastLinkHref: "/web/generalDisplay.html?id=our-services/designspark",
  weAcceptPaymentTypesLabel: "We accept",
  paymentOptionSource: "/jp_payment_options.svg",
  ConnectWithUsLable: "上で私たちに従ってください",







};
