module.exports = {
  Service: "Our Services",
  Legal: "Legal",
  AboutRS: "About Us",
  ServicesDisplayLinksCount: 7,
  legalDisplayedLinksCount: 4,
  aboutUSDisplayedLinksCount: 7,
  loginLabel: "Log In",
  registerButtonLabel: "Register",
  ServiceslDisplayLinksName: "Calibration,Delivery option,Order history,Parcel Tracking,Quotes,Returns,Schedule orders,",
  LegalLinknames: "Cookie Policy,Email Security,Privacy Policy,Website Terms,",
  AboutUSDisplayedLinksNames: "About Us,Careers,Corporate Group,Legal,Our Certifications,Press Centre,Worldwide",
  loginUserName: "MobileTest",
  RSOfficeAddress: "© RS Components AS. Fredrik Selmers vei 6, 10th floor, 0663 Oslo",
  RSContactNumber: "64 83 40 00",
  TalkToUsLabel: "Contact Us",
  SocialMediaLinks: 5,
  SocialMediaLinksLabel: "https://twitter.com/RSOnline_DK,https://www.linkedin.com/company/7099/,https://www.youtube.com/channel/UCZ6UzLdlJ8cLRcn5ooclCtA,https://www.instagram.com/rs_components/?hl=en,https://www.facebook.com/RSComponents",
  CompliancelinksLabel: "Website Terms,Privacy Policy,Cookie Policy,Email Security",
  loginPassword: "password",
  logOutText: "Log Out ",
  footer1HeaderFirstLinkHref: "/web/generalDisplay.html?id=our-services/calibration",
  footer1HeaderSecondLinkHref: "/web/generalDisplay.html?id=our-services/delivery&intcmp=NO-WEB-_-HP-FT-_-Jan-18-_-delivery",
  footer1HeaderLastLinkHref: "/web/generalDisplay.html?id=support/forward-orders",
  footer2HeaderFirstLinkHref: "/web/generalDisplay.html?id=om-RS/cookiepolicy",
  footer2HeaderSecondLinkHref: "/web/generalDisplay.html?id=om-RS/e-postsikkerhet",
  footer2HeaderLastLinkHref: "/web/generalDisplay.html?id=om-RS/internettvikaar",
  footer3HeaderFirstLinkHref: "/web/generalDisplay.html?id=om-RS",
  footer3HeaderSecondLinkHref: "https://www.electrocomponents.com/careers",
  footer3HeaderLastLinkHref: "http://www.rs-components.com/",
  weAcceptPaymentTypesLabel: "We accept",
  paymentOptionSource: "/no_payment_options.svg",
  ConnectWithUsLable: "Connect with us",


};
