module.exports = {
  Service: "Serviços",
  Legal: "Legal",
  AboutRS: "Sobre a RS",
  ServicesDisplayLinksCount: 7,
  legalDisplayedLinksCount: 4,
  aboutUSDisplayedLinksCount: 6,
  loginLabel: "Log In",
  registerButtonLabel: "Register",
  ServiceslDisplayLinksName: "Como realizar encomendas?,CotaçãoPLUS,Devoluções,Formas de entrega,Qualidade e Ambiente,RS para Particulares,Suporte Técnico,",
  LegalLinknames: "Aviso legal,Política de cookies,Política de privacidade,Segurança de emails,",
  AboutUSDisplayedLinksNames: "A RS no mundo,Condições de venda da RS,Grupo Electrocomponents,Sala de imprensa,Sobre a RS,Trabalhar na RS,",
  loginUserName: "MobileTest",
  RSOfficeAddress: "© Amidata S.A.U. Avenida de Europa, 19, 28224 - Pozuelo de Alarcón - Madrid - Espanha",
  RSContactNumber: "800 102 037",
  TalkToUsLabel: "Contacte-nos",
  SocialMediaLinks: 3,
  SocialMediaLinksLabel: "https://twitter.com/RSOnline_PT,https://www.linkedin.com/showcase/rs-components-iberia,https://www.youtube.com/channel/UCZ6UzLdlJ8cLRcn5ooclCtA",
  CompliancelinksLabel: "Website Terms,Privacy Policy,Cookie Policy,Email Security",
  loginPassword: "password",
  logOutText: "Log Out ",
  footer1HeaderFirstLinkHref: "/web/generalDisplay.html?id=servicos/metodos-encomendas",
  footer1HeaderSecondLinkHref: "/web/generalDisplay.html?id=servicos/cotacao-plus",
  footer1HeaderLastLinkHref: "/web/generalDisplay.html?id=servicos/ajuda-tecnica",
  footer2HeaderFirstLinkHref: "/web/generalDisplay.html?id=aboutRS&file=terms",
  footer2HeaderSecondLinkHref: "/web/generalDisplay.html?id=aboutRS&file=cookiePolicy",
  footer2HeaderLastLinkHref: "/web/generalDisplay.html?id=aboutRS/email-security",
  footer3HeaderFirstLinkHref: "http://www.rs-components.com/",
  footer3HeaderSecondLinkHref: "/web/generalDisplay.html?id=aboutRS&file=conditions",
  footer3HeaderLastLinkHref: "/web/generalDisplay.html?id=footer2",
  weAcceptPaymentTypesLabel: "Nós aceitamos",
  paymentOptionSource: "/pt_payment_options.svg",
  ConnectWithUsLable: "Siga-nos no",


};
